# Generated by Django 5.2.6 on 2025-09-27 13:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos_cursos/')),
            ],
        ),
        migrations.CreateModel(
            name='Herramienta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('enlace', models.URLField(blank=True, help_text='Enlace opcional si subes un archivo.', null=True)),
                ('archivo', models.FileField(blank=True, help_text='Sube el instalador o archivo .zip aquí.', null=True, upload_to='herramientas_archivos/')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='herramientas/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(default='pendiente', max_length=20)),
                ('click_count', models.IntegerField(default=0)),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('enlace', models.URLField(blank=True, help_text='Enlace opcional si subes un archivo.', null=True)),
                ('archivo', models.FileField(blank=True, help_text='Sube el juego o archivo .zip aquí.', null=True, upload_to='juegos_archivos/')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='juegos/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(default='pendiente', max_length=20)),
                ('click_count', models.IntegerField(default=0)),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Leccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.CharField(blank=True, help_text='Un resumen corto de la lección.', max_length=255)),
                ('contenido_html', models.TextField()),
                ('codigo_ejercicio', models.TextField(blank=True, help_text='Código inicial para la zona de práctica de esta lección.')),
                ('instrucciones_ejercicio', models.TextField(blank=True, help_text='El HTML con las instrucciones del ejercicio para la zona de práctica.')),
                ('puntos_xp', models.IntegerField(default=10, help_text='Puntos de experiencia ganados al completar la lección.')),
                ('orden', models.IntegerField(default=0)),
                ('usuarios_completado', models.ManyToManyField(blank=True, related_name='lecciones_completadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CasoPrueba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expresion_a_evaluar', models.TextField(help_text='El código a ejecutar o una descripción. Ej: mi_funcion(2, 3)')),
                ('resultado_esperado', models.TextField(help_text='La salida de texto exacta que se espera. Ej: 5')),
                ('leccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casos_prueba', to='cursos.leccion')),
            ],
        ),
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.curso')),
            ],
        ),
        migrations.AddField(
            model_name='leccion',
            name='modulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.modulo'),
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_xp', models.IntegerField(default=0)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('contenido', models.TextField()),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='post_imagenes/')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('me_gusta', models.ManyToManyField(blank=True, related_name='posts_con_me_gusta', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('me_gusta', models.ManyToManyField(blank=True, related_name='comentarios_con_me_gusta', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='cursos.post')),
            ],
        ),
    ]
