# Generated by Django 5.2.6 on 2025-09-08 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='herramienta',
            name='estado',
            field=models.CharField(default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='juego',
            name='estado',
            field=models.CharField(default='pendiente', max_length=20),
        ),
    ]
