# Generated by Django 5.2.6 on 2025-09-08 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_herramienta_estado_juego_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='herramienta',
            name='archivo',
            field=models.FileField(blank=True, help_text='Sube el instalador o archivo .zip aquí.', null=True, upload_to='herramientas_archivos/'),
        ),
        migrations.AddField(
            model_name='juego',
            name='archivo',
            field=models.FileField(blank=True, help_text='Sube el juego o archivo .zip aquí.', null=True, upload_to='juegos_archivos/'),
        ),
        migrations.AlterField(
            model_name='herramienta',
            name='enlace',
            field=models.URLField(blank=True, help_text='Enlace opcional si subes un archivo.', null=True),
        ),
        migrations.AlterField(
            model_name='juego',
            name='enlace',
            field=models.URLField(blank=True, help_text='Enlace opcional si subes un archivo.', null=True),
        ),
    ]
