# Generated by Django 5.2.6 on 2025-09-09 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0003_herramienta_archivo_juego_archivo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leccion',
            name='codigo_ejercicio',
            field=models.TextField(blank=True, help_text='Código inicial para la zona de práctica de esta lección.'),
        ),
    ]
