# Generated by Django 5.2.6 on 2025-09-09 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0004_leccion_codigo_ejercicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='leccion',
            name='instrucciones_ejercicio',
            field=models.TextField(blank=True, help_text='El HTML con las instrucciones del ejercicio para la zona de práctica.'),
        ),
    ]
