# Generated by Django 5.2.6 on 2025-09-10 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0005_leccion_instrucciones_ejercicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='herramienta',
            name='click_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='juego',
            name='click_count',
            field=models.IntegerField(default=0),
        ),
    ]
