# Generated by Django 5.2.6 on 2025-09-10 23:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0007_leccion_puntos_xp_perfil'),
    ]

    operations = [
        migrations.CreateModel(
            name='CasoPrueba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expresion_a_evaluar', models.TextField(help_text='El código a ejecutar. Ej: mi_funcion(2, 3)')),
                ('resultado_esperado', models.TextField(help_text='La salida de texto exacta que se espera. Ej: 5')),
                ('leccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casos_prueba', to='cursos.leccion')),
            ],
        ),
    ]
