# Generated by Django 5.2.6 on 2025-09-11 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0008_casoprueba'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casoprueba',
            name='expresion_a_evaluar',
            field=models.TextField(help_text='El código a ejecutar o una descripción. Ej: mi_funcion(2, 3)'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='cursos.post'),
        ),
    ]
