# Generated by Django 5.2.6 on 2025-09-14 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0009_alter_casoprueba_expresion_a_evaluar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='post_imagenes/'),
        ),
    ]
