# Generated by Django 5.2.6 on 2025-09-06 01:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_curso_modulo_curso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulo',
            name='curso',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cursos.curso'),
            preserve_default=False,
        ),
    ]
