# Generated by Django 5.2.6 on 2025-09-06 02:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0003_alter_modulo_curso'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='leccion',
            name='usuarios_completado',
            field=models.ManyToManyField(blank=True, related_name='lecciones_completadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
